### PR TITLE
Add conda/binder config

### PR DESCRIPTION
**Pull request by smithara**
I added a simple conda environment with recent package versions. The logic is that `environment-base.yml` describes the direct dependencies and used to generate the full `environment.yml` (that is platform-specific, i.e. linux. there is also another option to supply a conda-lock file that makes it work cross-platform). That's enough to make it load on binder (https://mybinder.org/v2/gh/IAGA-VMOD/IGRF13eval/binderize) but it can be overly slow to load.

When I ran the notebooks under this, I found that the contours are messed up:
image
could be due to some change in matplotlib but I didn't investigate. I'd recommend fixing the code so it works on the newer versions and use the same conda environment for development. We'll need to iterate a bit on what packages are required and then we can make the environment more fixed (so we are not debugging both dependencies and code at the same time).

Next I think I'll add some automation that will execute the notebooks and show them on github pages.

### CODE REVIEW

**Comment by ancklo** [comment]
Thanks Ashley,

I'm interested, when you set up binder, how do you tell it which environment file to use and where to find it? Will it look in the ``binder`` directory and take ``environment.yml`` by default? (or does it load ``environment-base.yml``?)

I also checked the maps and found the same issue with the contours. Points at opposite borders get connected. This seems to be a bug of the matplot version we are using. @ciaranbe, could you check which version of ``matplotlib`` you used? Maybe we can revert to that version?

Alternatively, we could avoid contours or use Cartopy instead. However, I would like to avoid Cartopy as much as possible, mainly because it would force us to use LGPL license, which is more restrictive than MIT and may be incompatible with some packages we would like to use in the future. Of course, if you are fine with this, I won't object.

**Comment by smithara** [comment]
Binder uses `environment.yml` (it uses a tool called [repo2docker](https://repo2docker.readthedocs.io/en/latest/configuration/index.html) underneath that can use a number of different configuration files)

Binder looks for a specific named file `environment.yml`, either in project root or in the `binder/` or `.binder/` subdirectory, and uses that. In this case I added `environment-base.yml` which is non-standard and won't be used by binder. It's just helpful to have as a base from which to derive a full environment. Many repositories will use a simple environment file like that and it normally works well enough, but because it doesn't pin the transitive/indirect dependencies (dependencies of dependencies), you can still run into reproducibility problems - if you install it at a later time, you would get newer versions of transitive dependencies.

The bottom line is - create the environment from the `binder/environment.yml` on your machine to use for development (will only work on linux; but I'll change it to a cross-platform one if we need that). Then we will be sure to be using the same packages.

Re. Cartopy license. I'm not sure that that's a problem. I always get confused with copyright rules but my understanding is that simply using it does not limit our license options, because we are not distributing that code. Anyway I'm in favour of being more conservative and sticking with regular matplotlib. (though pygmt is another option now!)

I think it's better to fix the code and use the newer matplotlib (if that is indeed the problem). We upgraded the Swarm VRE last week and the same problem is found there too, and I'd like to offer the VRE as another way for people to use the code (quicker startup than Binder, and although it's not exactly reproducible it should be close enough)

**Comment by ciaranbe** [comment]
I pulled a fresh copy of Anaconda before Christmas and developed this on my Mac, so I thought I was all up to date. 

The version is:
```
matplotlib.__version__
Out[144]: '3.7.2'
```
which now seems to be a few releases behind the current 3.8.2 (`https://matplotlib.org/stable/users/release_notes`). I will upgrade the version on my laptop and see if that is what is causing the issue. I agree that we should keep the install as light as possible with matplotlib. Alternatively, could we change the environment back to 3.7 to see if the contourf issue is still there?

Do you mean it is slow to load or slow to run? Other than the call to create the maps, the rest of the code should run very quickly.

**Comment by smithara** [comment]
I just checked - it's introduced between matplotlib 3.7.2 and 3.8.1. I'm wondering if it might be a bug in the `contour` function.

Okay: I will downgrade the conda env here to matplotlib 3.7 and see if I can find the source of the problem in the meantime.

**Comment by smithara** [comment]
Binder is slow to start because it needs to either build or pull a container specific to the git commit being referenced. There's some complexity involved in whether it needs to build a new one or not (this is the slowest part). Also, sometimes the service is not reliable because it is over-subscribed!

Anyway, I have moved matplotlib down to 3.7 and made lock files (under `binder/lockfiles/`) which can be used for local development. I'll go ahead and merge this branch now.

You should be able to use the lock file locally to provide a consistent environment, e.g.:
```
conda create --name igrftest --file binder/lockfiles/conda-osx-64.lock
```
(just switch the name to the correct platform)

The lock files are a list of the specific packages used. This also means that conda doesn't need to do the slow environment solving before installing the packages.

**Pull request merged**
